### ISSUE TITLE
Cast Single Child To Array

### ISSUE THREAD

**Issue by jgbenito7** [kofile/react-tabs#1]
The requirements changed temporarily for ko-search-react, and now there is only one tab. Instead of completely removing `react-tabs` to get rid of the warning message and then adding it back in the future, is it possible to remove the warning and cast a single child to an array?

https://github.com/kofile/react-tabs/blob/master/modules/Controls.js#L17

**Comment by neezer** [comment]
A tabbed interface with only one tab is nonsensical; just render the content. This can be solved in the consumer application, not here.
